spring.application.name=observerr

# Database
spring.datasource.url=jdbc:postgresql://ep-soft-shape-atg138mj.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_L35TloRUOGiy
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8080

# JWT Config
jwt.secret=observerr-super-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000
jwt.refresh-expiration=604800000
jwt.issuer=observerr

# CORS
spring.web.cors.allowed-origins=http://localhost:5178
